### ISSUE TITLE
Incorrect documentation for certain example models in the Spice3 library

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#1274]
**Reported by anonymous on 18 Sep 2013 14:58 UTC**
In the documentation for the examples models in the Spice3 library, it is suggested to the user which variables to plot. For the following models, those plot variables do not exist:

Modelica.Electrical.Spice3.Examples.Nand
Modelica.Electrical.Spice3.Examples.Nor
Modelica.Electrical.Spice3.Examples.FourInverters
Modelica.Electrical.Spice3.Examples.InvertersExtendedModel
Modelica.Electrical.Spice3.Examples.InvertersApartRecord
Modelica.Electrical.Spice3.Examples.Inverter

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1274

**Comment by beutlich** [comment]
Resolved in master.
