### ISSUE TITLE
Test library for Modelica tool capability

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#1291]
**Reported by fcasella on 26 Sep 2013 14:57 UTC**
The ModelicaTest library is designed to test the models of the MSL, and only as a side effect to test the ability of Modelica tool to use all the language features and solve all the mathematical problems that show up in the MSL.

A library to test the capabilities of Modelica tools to solve certain classes of mathematical problems that can be formulated using Modelica, and possibly to do it efficiently or reliably, in parallel, over the cloud, etc, should be promoted and maintained by the MA. As such, it should contain categorized test cases for difficult initialization problems, numerically critical models, high-index models, overconstrained models, very large sparse models, hybrid models, etc. It might use the MSL when that is convenient, but that won't necessarily be appropriate, as MSL models tend to be rather cumbersome and might not be optimal to spot problems and solve them quickly.

Tool vendors already have such libraries for internal testing and development; for instance, the Open Source Modelica Consortium has developed a large test suite for internal development of OMC. It would be interesting and in the spirit of the Modelica library to combine all these efforts together for the benefit of the community, and also to facilitate new tool vendors in their effort to provide good Modelica tools. 

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1291

**Comment by beutlich** [comment]
@casella Your [ScalableTestSuite](https://github.com/casella/ScalableTestSuite) does the job.
