### ISSUE TITLE
Documentation text for RealVectorInput and IntegerVectorInput

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#1373]
**Reported by anonymous on 2 Dec 2013 15:38 UTC**
The documentation layer text for Modelica.Blocks.Interfaces.RealVectorInput and Modelica.Blocks.Interfaces.IntegerVectorInput each have the text: 
  _Connector with one input signal of type Boolean._ 
but I guess this should be Real and Integer respectively.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1373

**Comment by beutlich** [comment]
Resolved by bd2585b7a01de7022d9d021c3611dc43e3c4f873.
