### ISSUE TITLE
Identifier typo in ModelicaTest.MultiBody.Parts.Rotor1D.Beveal1d

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#1604]
**Reported by beutlich on 12 Nov 2014 08:10 UTC**
ModelicaTest.MultiBody.Parts.Rotor1D.Beveal1d should correctly be named Bevel1D.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1604

**Comment by beutlich** [comment]
Is backwards-compatibility also an issue for ModelicaTest?

**Comment by MartinOtter** [comment]
No (ModelicaTest needs not be backwards compatible)

**Comment by beutlich** [comment]
Resolved by 1bb12fac7021fac8887223c2269b495dd4914939 in master.
