### ISSUE TITLE
Rename pulsStart of BooleanPulse

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#1835]
**Reported by anonymous on 13 Nov 2015 14:55 UTC**
Protected variable Modelica.Blocks.Sources.BooleanPulse.pulsStart probably should be renamed to Modelica.Blocks.Sources.BooleanPulse.pulseStart.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1835

**Comment by beutlich** [comment]
Since this parameter is protected, no conversion script should be necessary.
