### ISSUE TITLE
Consistent use of term technologieparameters

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#1864]
**Reported by beutlich on 16 Dec 2015 23:03 UTC**
There are the terms technologieparameters and technologyparameters used in Spice3. I guess only one of them should be used consistently.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1864

**Comment by modelica-trac-importer** [comment]
**Comment by ahaumer on 18 Dec 2015 12:14 UTC**
In my opinion there's no English term "technologie" but "technology".
I suppose that's a typo.
Since this is no big issue, I'm shifting the milestone.

**Comment by kristinmajetta** [comment]
Changed the term "technologie" into "technology" in Modelica.Electrical.Spice3
SHA-1: a91a0a91d7a43efa21abd328917667f1baa3f708
