### ISSUE TITLE
Utilize Modelica.Constants in MultiBody.World

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#1944]
**Reported by beutlich on 3 Mar 2016 12:05 UTC**
Utilize _Modelica.Constants.g_n_ in _Modelica.Mechanics.MultiBody.World.g_.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1944

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 3 Mar 2016 12:15 UTC**
Also _Modelica.Mechanics.MultiBody.World.mue_ could utilize _Modelica.Constants.G_ (multiplied by the mass of earth).

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 3 Mar 2016 12:16 UTC**

**Comment by beutlich** [comment]
Resolved in master.
