### ISSUE TITLE
Not quite 90 degrees, in Modelica.Mechanics.Rotational.Examples.CoupledClutches

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#1975]
**Reported by hansolsson on 4 Apr 2016 12:54 UTC**
Some example models use 1.57 as an approximation for pi/2 - that seems a bit inaccurate, and is especially an issue if you look at it in degrees:

Modelica.Mechanics.Rotational.Examples.CoupledClutches
Modelica.Blocks.Examples.PID_Controller

I would prefer to use more digits - even if it requires updated reference results for these two models.

Whereas the following ones use a good value (also for 45 degrees).
Modelica.Mechanics.Rotational.Examples.Backlash
Modelica.Fluid.Fittings.BaseClasses.Bends.CurvedBend.Geometry
Modelica.Mechanics.MultiBody.Examples.Elementary.RollingWheelSetDriving

(The ones for pi also use good values, and 2\*pi is only used in Modelica.Electrical.Analog.Examples.ShowSaturatingInductor for stopTime and it seems good enough.)

Clearly this is not a blocking issue.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1975

**Comment by beutlich** [comment]
@HansOlsson Resolved in the most straight-forward way in branches master and maint/3.2.2.
