### ISSUE TITLE
Documentation still refers to ModelicaAdditions

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#1982]
**Reported by beutlich on 11 Apr 2016 18:24 UTC**
Documentation of Modelica.Blocks.Logical.ZeroCrossing refers to ModelicaAdditions.Blocks.Discrete.TriggeredSampler but could be Modelica.Blocks.Discrete.TriggeredSampler.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1982

**Comment by beutlich** [comment]
Resolved in branches master and maint/3.2.2.
