### ISSUE TITLE
Modelica.Utilities.Examples.ReadRealMatrixFromFile issue

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#1990]
**Reported by peter&#46;lundberg on 28 Apr 2016 08:21 UTC**
The variable:

`parameter String file = ...`

is declared but never used.
The first two uses of (yet undeclared) "file1" should probably be replaced by "file".

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1990

**Comment by beutlich** [comment]
Resolved in master and maint/3.2.2.
