### ISSUE TITLE
MinGW gcc libraries for MSL 3.2.2 needs rebuild

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#1992]
**Reported by peter&#46;lundberg on 28 Apr 2016 14:38 UTC**
The libraries 

libModelicaIO.a
libModelicaMatIO.a
libzlib.a

under Modelica\Resources\Library\win{32,64} needs rebuild to match the source.
Only libModelicaStandardTables.a seems up to date.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1992

**Comment by modelica-trac-importer** [comment]
**Modified by dietmarw on 28 Apr 2016 15:06 UTC**

**Comment by beutlich** [comment]
@d94pn See #2273 for the latest binaries - including MinGW.
