### ISSUE TITLE
Connection to disabled frame_resolve

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#1999]
**Reported by hansolsson on 23 May 2016 08:56 UTC**
Modelica.Mechanics.MultiBody.Examples.Rotational3DEffects.ActuatedDrive 
and 
Modelica.Mechanics.MultiBody.Examples.Rotational3DEffects.MovingActuatedDrive
have connections to disabled frame_resolve connectors (for torque).

I don't see any explanation for this, and just believe it is a bit odd.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1999

**Comment by beutlich** [comment]
@MartinOtter I wanted to delete both invalid connect statements but wondered why they have set `LinePattern.Dot` for the connection lines set by purpose.

**Comment by HansOlsson** [comment]
> @MartinOtter I wanted to delete both invalid connect statements but wondered why they have set LinePattern.Dot for the connection lines set by purpose.

@beutlich The pattern likely means nothing and the explanation is as follows:
If you draw the connection line **from** the resolve-frame in Dymola (assuming it is enabled) the connection-line will "inherit" the LinePattern.Dot from that connector (same logic as for inheriting color).
