### ISSUE TITLE
Modelica.Fluid.Examples.DrumBoiler: incorrect unit on output p_S

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#2000]
**Reported by dag on 24 May 2016 11:25 UTC**
The top-level output `p_S` in Modelica.Fluid.Examples.DrumBoiler.DrumBoiler has incorrect unit. The sensor value (in Pa) is converted to Bar using a gain-block. However, the unit is not adjusted so the unit remains Pa although the value is scaled.

The minimum update would be to add the appropriate unit on the output of `Pa2bar `with a modifier

```
y(unit="bar")
```
I think an even better change would be to delete the components `Pa2bar `and `K2degC` altogether, because the outputs from the corresponding sensors already have the displayUnits we want.

 

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2000

**Comment by modelica-trac-importer** [comment]
**Comment by rfranke on 18 Jun 2016 10:06 UTC**
Good point. It is not an option to just remove the conversion blocks, because the global outputs are intended for model export, where the actual values must be scaled appropriately, not just the display. 

Think of the use case that one wants to build a controller around the DrumBoiler model, e.g. using Modelica.Blocks. It is very unlikely that the controller signals would be scaled in Pascal or Kelvin anywhere in the world.

The dedicated Celsius.FromKelvin K2degC is working correctly. We might add dedicted `toBar` and `fromMW` blocks to MSL. Where?

Alternatively: Modelica sensors should support unit conversion of the signal values that can be modified for the application at hand. An imperial application would most likely want to use psi and degF.

**Comment by modelica-trac-importer** [comment]
**Modified by rfranke on 18 Jun 2016 10:15 UTC**

**Comment by beutlich** [comment]
@rfranke Would Modelica.SIunits.Conversions.to_bar be an option?

**Comment by DagBruck** [comment]
@beutlich The minimum change that fixes the problem is to add the `y(unit="bar")` modifier.

**Comment by henrikt-ma** [comment]
Hej!

Tack för senast.

Märkte du att Hans placerade dig i gruppen som skulle styra upp tolkningen av arrowSize?
https://trac.modelica.org/Modelica/ticket/1894 <https://trac.modelica.org/Modelica/ticket/1894>

Jag har gjort ett konkret förslag som jag hoppas vi ska kunna göra klart och få med i 3.4.  Jag räknar med att Stefan Vorkoetter ger sina synpunkter så fort han är på benen hemma i Kanada igen.


Henrik

**Comment by beutlich** [comment]
Resolved in master by #2197.
