### ISSUE TITLE
Use of undeclared variables in Dialog.enable, Modelica.Mechanics.MultiBody

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#2004]
**Reported by hansolsson on 3 Jun 2016 11:45 UTC**
Undeclared variable: multiColoredSurface
in the Dialog.enable attribute of color declared in class Modelica.Mechanics.MultiBody.Visualizers.VoluminousWheel
\--
See also #2003

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2004

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 18 Oct 2016 12:30 UTC**

**Comment by beutlich** [comment]
Resolved in master and maint/3.2.2.
