### ISSUE TITLE
Modeling of Modelica.Electrical.Analog.Examples.OpAmps.SignalGenerator

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#2017]
**Reported by efredriksson on 21 Jun 2016 07:55 UTC**
I have a question regarding the model SignalGenerator. Running the model in multiple tools result in that we have one state c.v with discontinuous first derivative. The discontinuities wouldn't be a problem if they where associated with events but in this model, there are no event generating expressions. So my question is if this is an appropriate model? 

Attached is a figure of the state and state derivative. Notice the jumps in the derivative and that there are no events in this model. 

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2017

**Comment by dietmarw** [comment]
![image](https://cloud.githubusercontent.com/assets/9332/21981099/299b1332-dbe6-11e6-907e-c6da7d8ffede.png)

**Comment by beutlich** [comment]
I believe it could be improved if Modelica.Electrical.Analog.Ideal.IdealizedOpAmpLimted models the limiter the same way as Modelica.Blocks.Nonlinear.Limiter.

**Comment by beutlich** [comment]
After 9d5bc998bbe08a153fd622622400e744704a4257 Modelica.Electrical.Analog.Examples.OpAmps.SignalGenerator generates 20 state events for the voltage saturation.
