### ISSUE TITLE
Relational Blocks describe input as Boolean

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#2044]
**Reported by jriel on 10 Aug 2016 22:03 UTC**
The documentation for, say, Modelica.Blocks.Logical.Greater, describes the inputs as "Connector of first Boolean input signal".  They are declared as Real, not Boolean.

The fix should be to Modelica.Blocks.Interfaces.partialBooleanComparison.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2044

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 11 Aug 2016 09:07 UTC**

**Comment by beutlich** [comment]
@JoeRiel Fixed in branches master and maint/3.2.2.

**Comment by beutlich** [comment]
See also https://trac.modelica.org/Modelica/ticket/2168.
