### ISSUE TITLE
Bug in Modelica.Fluid.Examples.IncompressibleFluidNetwork

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#205]
**Reported by dietmarw on 9 Sep 2009 16:27 UTC**
When runnung the fluid example `Modelica.Fluid.Examples.IncompressibleFluidNetwork` the simulation will fail if one simple leaves the "valve1" closed.

When one sets valveOpening1(height=-1) the simulation will terminate
with an error message.

The tool shows:
  ```
... Error message from dymosim
At time T = 3.000001e+00 and stepsize
H = 1.164153e-13 the corrector could not
converge because IRES was equal to minus one.
Integration will be terminated.
```

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/205

**Comment by modelica-trac-importer** [comment]
**Modified by dietmarw on 31 Oct 2011 08:45 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 2 Aug 2012 13:08 UTC**
Just tested this again and for me it works. So it looks like it was perhaps a tool issue.

**Comment by modelica-trac-importer** [comment]
**Modified by dietmarw on 2 Aug 2012 13:33 UTC**

**Comment by Abantika-2409** [comment]
I am running a simulation on a building (two classrooms) with a VAV system with Indirect evaporative cooling. and the building also has night cooling with controllable windows. I get the same error during the simulation. I  run the simulation from (1st June to 31st August). When I run the simulation from day 58 (July 28th ) to day 68 (August 7th) the simulation runs. However from Day 0 if I start the simulation, I get this same error on day 13. How did you solve this error in your model?
