### ISSUE TITLE
Incorrect variables in description of stateSelect parameter in Translatation components

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#2059]
**Reported by jriel on 9 Sep 2016 22:43 UTC**
The components in Modelica.Mechanics.Translational.Components with a **stateSelect** parameter describe the parameter as "Priority to use phi_rel and w_rel as states".  That was clearly copied from the equivalent Rotational components; the correct variables are presumably s_rel and v_rel.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2059

**Comment by beutlich** [comment]
@JoeRiel Fixed in branches master and maint/3.2.2.
