### ISSUE TITLE
Modelica.Blocks.Nonlinear.VariableDelay should declare delayMax as duration

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#2067]
**Reported by jriel on 20 Sep 2016 04:49 UTC**
The parameter delayMax should be declared as type Modelica.SIunits.Duration rather than simply as Real.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2067

**Comment by beutlich** [comment]
@JoeRiel Resolved in branches master and maint/3.2.2.
