### ISSUE TITLE
Vector.interpolate doc should mention it is linear

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#2068]
**Reported by pierre&#x2e;haessig on 22 Sep 2016 14:35 UTC**
I believe that the docstring of Vector.interpolate doesn't mention the fact it's linear. Looking at the source, it is!

Here is a minimalistic proposition: https://github.com/modelica/Modelica/pull/6

First sentence becomes:

The function call Vectors.interpolate(x,y,xi) interpolates **linearly** in vectors ....

(I didn't put bold in the actual code, although an italic formatting may be appropriate)

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2068

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 30 Sep 2016 10:37 UTC**

**Comment by beutlich** [comment]
@pierre-haessig Resolved in branches master and maint/3.2.2.

**Comment by pierre-haessig** [comment]
thanks!
