### ISSUE TITLE
Parameter enableNoise depends per default on settings in GlobalSeed

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#2079]
**Reported by tobolar on 13 Oct 2016 08:59 UTC**
Since the availibility of multiple noise signals generally applies for a complete model where they are used, the parameter `enableNoise` in Modelica.Blocks.Interfaces.PartialNoise should be per default dependent on `globalSeed.enableNoise` from Modelica.Blocks.Noise.GlobalSeed

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2079

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 13 Oct 2016 20:40 UTC**

**Comment by beutlich** [comment]
@tobolar Can you please provide a PR for this enhancement. Thank you very much.

**Comment by tobolar** [comment]
Sorry, but what does PR stand for? [http://www.abbreviations.com/PR](http://www.abbreviations.com/PR)

**Comment by xie-dongping** [comment]
@tobolar

PR stands for pull request in GitHub.
https://help.github.com/articles/about-pull-requests/

**Comment by tobolar** [comment]
I see. Then I will prepare PR.

**Comment by beutlich** [comment]
Resolved both in master and maint/3.2.2.
