### ISSUE TITLE
Math.Random functions special and distributions only succeed for default arguments

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#2081]
**Reported by beutlich on 17 Oct 2016 19:26 UTC**
If ModelicaTest.Math.Random.distributions is called with first input argument nPoints smaller than default value 1000, e.g., 100, then the assertions fail since the error value thresholds are only valid for the unmodified default values. Thus it is without use to have nPoints (and erfRange) as inputs arguments available.

Reproduction: ModelicaTest.Math.Random.distributions(nPoints=100)

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2081

**Comment by MartinOtter** [comment]
The reason for the issues have been that an approximate derivative with a two-side difference quotient is used to check that the same result is obtained by using the analytic solution of the distributions functions. However, this approximate, numeric solution is only precise enough, if there are enough points and the derivative is not computed at a discontinuous border. Both issues have been fixed (the first one by requireing that nPoints >= 1000).
