### ISSUE TITLE
Missing comment for String parameter Modelica.Electrical.Digital.Memories.DLATRAM.fileName

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#2082]
**Reported by beutlich on 18 Oct 2016 11:57 UTC**
Whereas Memories.DLATROM.fileName has a comment, Memories.DLATRAM.fileName misses a comment.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2082

**Comment by beutlich** [comment]
@kristinmajetta I fixed in in branches master and maint/3.2.2.
