### ISSUE TITLE
Wrong loadSelector.filter annotation in Modelica.Electrical.Digital.Memories.DLATRAM and DLATROM

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#2085]
**Reported by beutlich on 18 Oct 2016 12:38 UTC**
The loadSelector.filter annotation in Memories.DLATRAM and DLATROM says it supports MATLAB MAT files, which is wrong. Only text files are supported (that are parsed by function getMemory using Utilities.Streams.readLine and Utilities.Strings.scanInteger).

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2085

**Comment by beutlich** [comment]
@kristinmajetta I fixed in in branches master and maint/3.2.2.
