### ISSUE TITLE
Line color of Sources.V_constant, Semiconductors.D_DIODE and Semiconductors.C_Capacitor icons (Modelica.Electrical.Spice3)

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#2086]
**Reported by beutlich on 18 Oct 2016 13:42 UTC**
Should Sources.V_constant be better drawn in blue (instead black) to better match the other components or the connect color?

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2086

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 18 Oct 2016 13:50 UTC**
Please do also look at Semiconductors.C_Capacitor.

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 18 Oct 2016 13:50 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 18 Oct 2016 13:56 UTC**
And also in Semiconductors.D_DIODE.

**Comment by kristinmajetta** [comment]
Changed linecolor from black to blue in Modelica.Electrical.Spice3.Sources.V_constant
73ee16e7ae5408a7eb65123bacec88b2dd2f7e2d

**Comment by beutlich** [comment]
Thanks. What about D_DIODE and C_Capacitor?

**Comment by beutlich** [comment]
Resolved in master.
