### ISSUE TITLE
Comment of Modelica.Electrical.Spice3.Internal.Rsemiconductor.ResistorModelLineParams and ResistorVariables

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#2088]
**Reported by beutlich on 18 Oct 2016 14:10 UTC**
Comments of Internal.Rsemiconductor.ResistorModelLineParams and Internal.Rsemiconductor.ResistorVariables speak about diode variables. Should it be resistor instead?

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2088

**Comment by beutlich** [comment]
@kristinmajetta Any idea :question: Should be easy to fix then.

**Comment by beutlich** [comment]
Resolved in master branch.
