### ISSUE TITLE
Utilize outerProduct in functions of Modelica.Mechanics.MultiBody.Frames

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#2091]
**Reported by beutlich on 19 Oct 2016 06:16 UTC**
Rewrite the term `[e]*transpose([e])` in Frames.planarRotation, Frames.smallRotation, Frames.from_Q, Frames.multipleResolve1, Frames.multipleResolve2, Frames.to_T and Frames.to_T_inv by `outerProduct(e,e)` to avoid the duplicated array construction and make it more readable and economic.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2091

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 26 Oct 2016 10:36 UTC**
Replying to [ticket:2091 beutlich]:
> Rewrite the term `[e]*transpose([e])` in Frames.planarRotation, Frames.smallRotation, Frames.from_Q, Frames.multipleResolve1, Frames.multipleResolve2, Frames.to_T and Frames.to_T_inv by `outerProduct(e,e)` to avoid the duplicated array construction and make it more readable and economic.

I agree with the change.
However, I prefer if it isn't too rushed - since it could possibly cause failure to translate with current version of our tools in some odd scenario. (Will be corrected.)

**Comment by modelica-trac-importer** [comment]
**Comment by anonymous on 26 Oct 2016 11:42 UTC**
Replying to [comment:1 hansolsson]:
> Replying to [ticket:2091 beutlich]:
> > Rewrite the term `[e]*transpose([e])` in Frames.planarRotation, Frames.smallRotation, Frames.from_Q, Frames.multipleResolve1, Frames.multipleResolve2, Frames.to_T and Frames.to_T_inv by `outerProduct(e,e)` to avoid the duplicated array construction and make it more readable and economic.
> 
> I agree with the change.
> However, I prefer if it isn't too rushed - since it could possibly cause failure to translate with current version of our tools in some odd scenario. (Will be corrected.)

Do not worry, there is no rush.

**Comment by beutlich** [comment]
Resolved by dcc02ba3e6229415f3d87ee8522768fd4342513f in master.
