### ISSUE TITLE
Tables/Matrices: Update Matio Library to v1.5.10

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#2092]
**Reported by beutlich on 22 Oct 2016 12:40 UTC**
Now that matio v1.5.10 is about to be released ModelicaMatIO should be updated to this version.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2092

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 22 Oct 2016 12:40 UTC**

**Comment by beutlich** [comment]
164e1c2cfe5ad2170c0d08862041279e12f60fe6 updated Matio to v1.5.11. (There was no official MSL release containing Matio v1.5.9 or v1.5.10).
