### ISSUE TITLE
Modelica.Blocks.Sources.Exponentials should be a block

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#2102]
**Reported by jriel on 10 Nov 2016 18:32 UTC**
It has type model rather than block.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2102

**Comment by modelica-trac-importer** [comment]
**Comment by jriel on 10 Nov 2016 18:40 UTC**
Similarly for Modelica.Blocks.Routing.BooleanPassThrough, IntegerPassThrough, and RealPassThrough.

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 11 Nov 2016 07:46 UTC**

**Comment by beutlich** [comment]
That was changed in ee9a1a29568c2815a0e568719f25482a50d388c7 from block to model. @DagBruck Did you change the type by accident or purpose?

**Comment by beutlich** [comment]
Pointing to @JoeRiel.

**Comment by beutlich** [comment]
@DagBruck Any objections to change Exponentials back to block?

**Comment by beutlich** [comment]
Resolved in master.

**Comment by beutlich** [comment]
Leave a comment
