### ISSUE TITLE
Invalid Line.fillPattern annotation in Modelica.Electrical.Digital.Examples.Utilities.Counter3

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#2107]
**Reported by beutlich on 11 Nov 2016 09:34 UTC**
There are ten connect statements in Examples.Utilities.Counter3 where Line.fillPattern is set to FillPattern.Solid. According to MLS 3.3r1 section 18.6.5.1 there is no variable fillPattern in type Line, but there is variable pattern of type LinePattern.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2107

**Comment by beutlich** [comment]
@AHaumer @kristinmajetta @ECClauss I fixed it for branches master and maint/3.2.2.

@MartinOtter Interestingly, the error was in the MSL since v3.0, introduced by c340760a9e210260edf6ab82bcffa75836c8f95a, but it also looked strange before (in v2.2.x) with `fillPattern=1`
