### ISSUE TITLE
Add Modelica.Icons.FunctionsPackage

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#2115]
**Modified by beutlich on 9 Dec 2016 10:46 UTC**
Would be nice if there was a FunctionsPackage icon for packages containing functions. I do miss that icon quite a lot.

----

**Reported by beutlich on 15 Nov 2016 08:02 UTC**
Would be nice if there were a FunctionsPackage icon for packages containing functions. I do miss that icon quite a lot.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2115

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 9 Dec 2016 10:21 UTC**
See also https://github.com/modelica/Modelica_DeviceDrivers/commit/d09a241eba7c3163ece3a085b6ee486e87ab0661 for an example.

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 9 Dec 2016 10:46 UTC**

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 9 Dec 2016 11:18 UTC**

**Comment by beutlich** [comment]
See https://github.com/tbeu/ExternData/commit/3c8edfbd53075d5b72fe0e61e597224e6cf4ad65 for another example.

**Comment by beutlich** [comment]
@d-hedberg If you do not have time to design a new icon, just tell me wich one you like more and I can add it for you.

**Comment by beutlich** [comment]
@d-hedberg Did you have a look at this in the mean-time?

**Comment by d-hedberg** [comment]
The one in https://github.com/tbeu/ExternData/commit/3c8edfbd53075d5b72fe0e61e597224e6cf4ad65 would be my preferred choice.

**Comment by beutlich** [comment]
Resolved in master and maint/3.2.2.
