### ISSUE TITLE
Electrical icons not homogeneous

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#2117]
**Reported by massimo&#46;ceraolo on 15 Nov 2016 13:54 UTC**
The "%name" field in Modelica.Electrical.MultiPhase.Sensors is too near to the sensor's circle, especially in comparison to the  position in which it is in Modelica.Electrical.Analog.Sensors.
Moreover in power sensors the "name" field is present only in the MultiPhase MSL library.

I would suggest to :
- modify the position of the field in the MultiPhase sublibrary to make it similar to the one in sublibrary Analog.Sensors
- remove "name" from Modelica.Electrical.MultiPhase.Sensors.PowerSensor

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2117

**Comment by beutlich** [comment]
Point to @ceraolo.

**Comment by christiankral** [comment]
This issue is taken care of in #2215
