### ISSUE TITLE
C_default not defined in Modelica.Media.Interfaces.PartialMedium

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#2121]
**Reported by rubenbaetens on 24 Nov 2016 09:41 UTC**
Modelica.Media.Interfaces.PartialMedium defines T_default, h_default, X_default and p_default, but no C_default. It would be better to add C_default = fill(0, Medium.nC) to the MSL so that all is consistent. As such, users can use C_default as the default start value and the default concentration for Boundary_pT, and can reassign this value in the medium.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2121

**Comment by beutlich** [comment]
Pointing to @rubenbaetens.

**Comment by beutlich** [comment]
@hubertus65 Any feedback on this enhancement?

**Comment by beutlich** [comment]
@rubenbaetens @casella Since this is [Hacktoberfest](https://twitter.com/hashtag/Hacktoberfest) and the library officers did not give any feedback I created #2364 now.
