### ISSUE TITLE
Fix the license info for the ModelicaServices library on the MA server

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#2133]
**Reported by fcasella on 13 Dec 2016 18:00 UTC**
It currently contains references to DLR and Dassault Systèmes, which should be removed and replaced by references to MA.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2133

**Comment by tbeu** [comment]
@casella Resolved in branches master and maint/3.2.2.
