### ISSUE TITLE
New function Modelica.Utilities.Strings.hashString is not listed in the package documentation table

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#2141]
**Reported by anonymous on 26 Dec 2016 21:15 UTC**
The newly introduced function Modelica.Utilities.Strings.hashString is missing in the package documentation table of Modelica.Utilities.Strings (after function sort).

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2141

**Comment by beutlich** [comment]
Resolved in master and maint/3.2.2.
