### ISSUE TITLE
Improve comment on Modelica.Utilities.System.getEnvironmentVariable.convertToSlash

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#2144]
**Reported by beutlich on 2 Jan 2017 14:31 UTC**
In function Modelica.Utilities.System.getEnvironmentVariable the comment on argument convertToSlash refers to `'result'`. It looks like `'result'` is a component of getEnvironmentVariable, but there is no such one. Should it be corrected to `'content'`?

```diff
@@ -28,7 +28,7 @@ function getEnvironmentVariable "Get content of en
   extends Modelica.Icons.Function;
   input String name "Name of environment variable";
   input Boolean convertToSlash =  false
-      "True, if native directory separators in 'result' shall be changed to '/'";
+      "True, if native directory separators in 'content' shall be changed to '/'";
   output String content
       "Content of environment variable (empty, if not existent)";
   output Boolean exist
```

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2144

**Comment by beutlich** [comment]
Resolved in master and maint/3.2.2.
