### ISSUE TITLE
Simplify Initialization of Modelica.Thermal.FluidHeatFlow.Interfaces.Partials.TwoPort

### ISSUE THREAD

**Issue by FrenkelJ** [modelica/Modelica#2148]
The initialization of extended models from Modelica.Thermal.FluidHeatFlow.Interfaces.Partials.TwoPort would be much easier if the variable h get as modification of the start attribute
`
Modelica.SIunits.SpecificEnthalpy h(start=medium.cp*T0) "Medium's specific enthalpy";
`

Ad least the example Modelica.Thermal.FluidHeatFlow.Examples.PumpAndValve would benefit from the additional information.

**Comment by casella** [comment]
@FrenkelJ can you open a ticket on the MSL issue tracker?

**Comment by sjoelund** [comment]
This is the MSL issue tracker. trac.modelica.org is read-only for MSL components.

**Comment by beutlich** [comment]
@casella Both the MA Webmaster, @AHaumer, @MartinOtter and me sent several mails that the MSL is now developed on GitHub, including issues. It also was tweeted by https://twitter.com/modelica/status/820906213806374912 two weeks ago.

**Comment by casella** [comment]
Sorry folks, the management of the Modelica Conference papers obviously hit hard on me. Please be patient with me and allow me to catch up again soon.

That said, I agree with @FrenkelJ proposal

**Comment by beutlich** [comment]
Also cherry-picked to maint/3.2.2 branch.
