### ISSUE TITLE
Unknown choices in  Modelica/Modelica/Fluid/Fittings.mo

### ISSUE THREAD

**Issue by eshmoylova** [modelica/Modelica#2156]
In several functions in Modelica/Modelica/Fluid/Fittings.mo the names that appear in choices annotations refer to classes that do not exist. Code block starting on line 1298:
```
      choices(
      choice=Modelica.Fluid.Fittings.Utilities.QuadraticTurbulent.LossFactorData.wallFriction(),
      choice=Modelica.Fluid.Fittings.Utilities.QuadraticTurbulent.LossFactorData.suddenExpansion(),
      choice=Modelica.Fluid.Fittings.Utilities.QuadraticTurbulent.LossFactorData.sharpEdgedOrifice()));
```
There is no package Utilities in Modelica.Fluid.Fittings. Perhaps it is supposed to be BaseClasses instead of Utilities. 

Another block with unknown names is:
```
      choices(
      choice=BaseClasses.PressureLosses.QuadraticTurbulent.LossFactorData.wallFriction(),
      choice=BaseClasses.PressureLosses.QuadraticTurbulent.LossFactorData.suddenExpansion(),
      choice=BaseClasses.PressureLosses.QuadraticTurbulent.LossFactorData.sharpEdgedOrifice()));
```
It appears on lines 1340, 1438, 1480, and 2033. There is no package PressureLosses in BaseClasses. It should be BaseClasses.QuadraticTurbulent.LossFactorData....

The problem appears in the master branch, and in maint/3.2.2. The line numbers are the same in both branches.

**Comment by beutlich** [comment]
Resolved in master and maint/3.2.2 branches.
