### ISSUE TITLE
Missing comments for ComplexMath.TransferFunction and ShowTransferFunction

### ISSUE THREAD

**Issue by beutlich** [modelica/Modelica#2166]
Models Modelica.ComplexBlocks.ComplexMath.TransferFunction and Modelica.ComplexBlocks.Examples.ShowTransferFunction added by #1850 for MSL v3.2.2 miss a descriptive comment.

**Comment by AHaumer** [comment]
resolved by SHA-1: b8d6d31003ba661a9f67ca9581c8c6e4b5bcdbc0 for trunk
resolved by SHA-1: e1dfd65e0481db6bf304768a19c3b5d9a254f296 for maint/3.2.2
