### ISSUE TITLE
Use port for stator current input in Modelica.Magnetic.QuasiStatic.FundamentalWave.Losses.PermanentMagnetLosses

### ISSUE THREAD

**Issue by JoeRiel** [modelica/Modelica#2174]
The stator current input to the PermanentMagnetLosses component is an input, but has no connection so the model cannot be used in a graphical environment.

**Comment by christiankral** [comment]
@ahaumer This issue is related with #1752.

**Comment by AHaumer** [comment]
duplicate #1752, therefore closed
