### ISSUE TITLE
Invisible connection line in Modelica.Magnetic.FluxTubes.Examples.MovingCoilActuator.Components.PermeanceActuator

### ISSUE THREAD

**Issue by HansOlsson** [modelica/Modelica#2179]
When correcting #2152 I found that there was one remaining invisible line in MSL.
I don't see any reason for this, and will make a pull request to correct it.

**Comment by dietmarw** [comment]
Hans, just for save you some work. If you have some minor things that you can fix easily then a pull request is probably good enough since it gets its number and one can discuss on the pull request itself. So probably no need to also additional create an issue (though I appreciate the effort).
