### ISSUE TITLE
Frequency parameter of Signal2mPulse should not be hidden when filter is disabled

### ISSUE THREAD

**Issue by JoeRiel** [modelica/Modelica#2195]
The block Modelica.Electrical.PowerConverters.ACDC.Control.Signal2mPulse has a frequency parameter, f, that is declared as
`        parameter Modelica.SIunits.Frequency f=50 "Frequency"
          annotation (Dialog(tab="Filter", enable=useFilter));`
The annotation hides the parameter when useFilter is true, however, the parameter is also used in the gain block which is still active.  The annotation should be removed.

**Comment by AHaumer** [comment]
Even more: the filter's cut-off frequency should be parameterized by the parameter fCut.
Resolved by SHA-1: fa9e012c56e9a4344861843838401cfd0543918b for maint/3.2.2
Resolved by SHA-1: 4cfd0a09189571ff2970571525b486ab5fe9598b for master
