### ISSUE TITLE
Add MultiSensor to Analog, MultiPhase and QuasiStationary electrical packages

### ISSUE THREAD

**Issue by christiankral** [modelica/Modelica#2201]
The mechanical packages provide multi sensors:

- Modelica.Mechanics.Rotational.Sensors.MultiSensor
- Modelica.Mechanics.Translational.Sensors.MultiSensor

Their sensor outputs are 
- force | torque 
- speed | angular speed
- power | power

Such multi sensors are missing in the electrical libraries and shall thus be added; their sensor outputs are:

- instantaneous current(s)
- instantaneous voltages(s)
- instantaneous power(s) (and total power in case of the multi phase sensor)

**Comment by AHaumer** [comment]
I've created a repository https://github.com/AHaumer/ElectricalMultiSensors to develop and test these sensors. Already done: Analog, MultiPhase, QuasiStationary.SinglePhase. Still to be done: QuasiStationary.MultiPhase.
