### ISSUE TITLE
Documentation of Modelica.Blocks describes scalars as vectors

### ISSUE THREAD

**Issue by HansOlsson** [modelica/Modelica#2203]
When writing a reply to #2168  I noticed that some blocks have a scalar input but are described as if they have an input with many elements. That is confusing and likely a left-over from Modelica standard library version 1 (when they had an actual vector as input).

At least Modelica.Blocks.Math.Sqrt Modelica.Blocks.Math.Asin Modelica.Blocks.Math.Acos have this problem, but it is likely that there are more.

**Comment by HansOlsson** [comment]
Modelica.Blocks.Continuous.Integrator and Modelica.Blocks.Continuous.LimIntegrator are also described as element-wise operations; but have a single scalar input.

**Comment by beutlich** [comment]
@MartinOtter When will you be able to deal with it?
