### ISSUE TITLE
TimeTable does not assert that first time value is 0

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/Modelica#2209]
The `TimeTable` documentation clearly states that the first time value must be 0.  However, there is no corresponding assert in the implementation, and failing to satisfy the requirement leads to array indexing out of bounds, which at best will result in a generic out-of-bounds error message that won't be able to pinpoint the problem.  In the worst case, the out-of-bounds isn't detected, and the table produces invalid values without any indication of a problem.

**Comment by beutlich** [comment]
Resolved by 20fe8c918c71eee7325cef93dfa60b667753a102 in master.
