### ISSUE TITLE
Inductor, Transformer, etc. render poorly on non-white backgrounds

### ISSUE THREAD

**Issue by dietmarw** [modelica/Modelica#2210]
Basically a copy of #2031 but this time for the QuasiStationary components. Here it is even worse since arrows are used and hidden by the block.

**Comment by beutlich** [comment]
@svorkoetter Since you provided the fix for #2031 a new pull request for the QuasiStationary models is highly appreciated. Thank you!

**Comment by christiankral** [comment]
Fixed.
