### ISSUE TITLE
Incorrect Bode plot in Modelica_LinearSystem2

### ISSUE THREAD

**Issue by UlfNordstrom** [modelica/Modelica#2212]
Hi,

Issues have been found with the Bode plots in Modelica_LinearSystems2 2.3.4.

One problem (already reported to M. Otter, possibly fixed in the trunk) is that the matrices from "//Balance system" in Modelica_LinearSystems2.StateSpace.Plot.bodeMIMO are not use in the calculations under 
"// Perform computation from every input to every output", and this causes incorrect Bode plots.

Another issue is the attached model (in springdamper.txt), where the Bode plot is completely wrong. A screenshot of the correct Bode plot obtained using other software and the calculated state space representation of the model is attached.

![2017-03-17 12-14-24](https://cloud.githubusercontent.com/assets/26482906/24041063/269221e4-0b0c-11e7-952c-40445cb09aca.png)

[test_springdamper.txt](https://github.com/modelica/Modelica/files/850380/test_springdamper.txt)

Note that with Modelica_LinearSystems2 2.3.2 the first scenario is ok, but the springdamper model is not.

Best regards,
Ulf

**Comment by beutlich** [comment]
Please open an issue on [modelica/Modelica_LinearSystems2](https://github.com/modelica/Modelica_LinearSystems2).
