### ISSUE TITLE
Missing closing parenthesis in Modelica.Electrical.Analog.Ideal.IdealizedOpAmpLimted.useSupply

### ISSUE THREAD

**Issue by beutlich** [modelica/Modelica#2225]
Parameter useSupply of Modelica.Electrical.Analog.Ideal.IdealizedOpAmpLimted misses a closing parenthesis.

**Comment by kristinmajetta** [comment]
missing closing parenthesis for parameter useSupply added in Modelica.Electrical.Analog.Ideal.IdealizedOpAmpLimted.
SHA-1: b49faad5f9446abb703516653b56a5135b59df61

**Comment by beutlich** [comment]
Thanks.
