### ISSUE TITLE
Incorrect use of putenv in ModelicaInternal.c on modern macOS

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/Modelica#2235]
It seems that the fix for #1433 revealed incorrect use of `putenv` on modern macOS.  Quoting the documentation:
> The putenv() function takes an argument of the form ``name=value'' and is
> equivalent to:
>
>       setenv(name, value, 1);
>
> The string pointed to by string becomes part of the environment.  A pro-
> gram should not alter or free the string, and should not use stack or
> other transient string variables as arguments to putenv().  The setenv()
> function is strongly preferred to putenv().

**Comment by beutlich** [comment]
Resolved in master.
