### ISSUE TITLE
Matrices Riccati functions define array size in terms of non-input variable

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/Modelica#2240]
The functions `Matrices.discreteRiccati` and `Matrices.continuousRiccati` both define array sizes in terms of the non-input variable `H`, like so:
```Modelica
  output Real alphaReal[size(H, 1)] "Real parts of eigenvalue=alphaReal+i*alphaImag";
```

This is not allowed by section 12.2, which says:
> The dimension sizes not declared with (:) of each array result or array local variable [i.e., a non-input components] of a function must be either given by the input formal parameters, or given by constant or parameter expressions, or by expressions containing combinations of those (Section 12.4.4).

**Comment by beutlich** [comment]
Resolved in master.
