### ISSUE TITLE
Invalid ftp link in Math/Nonlinear.mo

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#2249]
**Reported by @d94pn on 2017-05-02T11:06:14+01:00**
 Hello,
The following FTP link is obsolete:
Math/Nonlinear.mo

`<a href=\"​ftp://ftp.inf.ethz.ch/doc/techreports/1998/306.ps\">​ftp://ftp.inf.ethz.ch/doc/tech-reports/1998/306.ps</a>`

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2186

**Comment by beutlich** [comment]
Resolved in master,
