### ISSUE TITLE
Modelica.Electrical.QuasiStationary.MultiPhase.Blocks.SingleToMultiPhase does not conjugate inputs

### ISSUE THREAD

**Issue by JoeRiel** [modelica/Modelica#2251]
The block is extended from ComplexSIMO:
` extends Modelica.ComplexBlocks.Interfaces.ComplexSIMO(final nout=m);`
As such it inherits the useConjugateInput boolean parameter.  The equations for the block, however, use u rather than uInternal, so the parameter has no effect. The solution is either to extend the block to use uInternal, or pass  final useConjugateInput = false in the extends statement.

The same issue exists with SymmetricalComponents, though there the parameter is a boolean vector.

**Comment by christiankral** [comment]
The parameter ``useConjugateInput`` was introduced for backwards compatibility reasons but the parameters were not set ``final useConjugateInput = false`` in the following models, as the conjugate complex input does not make sense: 
- ``Modelica.Electrical.QuasiStationary.MultiPhase.Blocks.SymmetricalComponents``
- ``Modelica.Electrical.QuasiStationary.MultiPhase.Blocks.FromSymmetricalComponents``
- ``Modelica.Electrical.QuasiStationary.MultiPhase.Blocks.SingleToMultiPhase``
