### ISSUE TITLE
Wording suggestion for Modelica.Blocks.Logical.Timer

### ISSUE THREAD

**Issue by zambitol** [modelica/Modelica#2257]
The description for the Modelica.Blocks.Logical.Timer component says:
When the Boolean input "u" becomes true, the timer is started and the output "y" is the time from the time instant where u became true. The timer is stopped and the output is reset to zero, once the input becomes false.
I'd like to suggest the following (or similar) for clarity:
When the Boolean input "u" becomes true, the timer starts and the output "y" is the time that has elapsed since "u" became true. When the input becomes false, the timer stops and the output is reset to zero.

**Comment by beutlich** [comment]
@zambitol Thanks for the suggestions. If you find more such improvements you simply can add a pull request against master branch.

Resolved in master.
