### ISSUE TITLE
Add adaptor components to Mechanics.Translational

### ISSUE THREAD

**Issue by beutlich** [modelica/Modelica#2269]
There are TorqueToAngleAdaptor and AngleToTorqueAdaptor in Modelica.Mechanics.Rotational.Components, however the corresponding elements are missing in Modelica.Mechanics.Translational.Components.

**Comment by beutlich** [comment]
@Claytex people are creative meanwhile, see there [Tech Blog](https://t.co/gsdpIlqkIB). 👍

**Comment by AHaumer** [comment]
Working on this issue.
I'll open a similar ticket for thermal and electric domain.

**Comment by dietmarw** [comment]
The added new components are missing any test models. Either in ModelicaTest or as runnable examples so that simulation errors can be checked for.

**Comment by AHaumer** [comment]
Sorry Dietmar to correct you: there is a test model (same as in Rotational).
Modelica.Mechanics.Translational.Examples.GenerationOfFMUs
Anyhow: Thanks for reopening this ticket. 
I'm developing a solution based on the same partial adapter for different domains (electric, thermal). 
Therefore I'm going to close #2399 and #2400.

**Comment by AHaumer** [comment]
Partly resolved with general solution (Translational, HatTransfer). Remaining: Electrical.Analog
