### ISSUE TITLE
Unify communication intervals of electric machine models

### ISSUE THREAD

**Issue by christiankral** [modelica/Modelica#2279]
The communication interval of the electric machine models are set differently in the Machines and FundamentalWave examples. All communication intervals shall be unified to ``experiment(Interval=1E-4,...)`` in order to 
- more accurately show transient torque characteristics 
- better compare results across Machines and FundamentalWave examples

**Comment by christiankral** [comment]
@GallLeo I am not sure what impact this change on regression tests has. It may be possible that we have to create a new baseline data set for comparing future MSL versions -- depending on the implementation of the regression test tool (which I am not familiar with).

**Comment by christiankral** [comment]
The only exceptions are (due to the longer simulation time):
- SMEE_Generator
- SMEE_Generator_MultiPhase 

For these examples ``experiment(Interval=1E-3,...)``

**Comment by beutlich** [comment]
@christiankral Is this issue resolved?
