### ISSUE TITLE
Linear interpolation fails in CombiTimeTable for large values of time

### ISSUE THREAD

**Issue by Mathadon** [modelica/Modelica#2282]
When a `CombiTimeTable` is used to interpolate a data stream with large values of time (i.e. unix time stamps in the order of 1.4e9), the linear interpolation fails. I.e. the returned result changes discontinuously:
![screen shot 2017-07-19 at 15 00 06](https://user-images.githubusercontent.com/5970879/28367943-02eddd8a-6c93-11e7-9e59-68e3d48c43cf.png)

The top graph shows the wrong result, for `time > 1.42e9`. Below is the result when I subtracted 1.42e9 from the time column in the source file. The interpolation then does work.

Note that the top result is not equal to the constant segment implementation: the pieces still have a slope, it's just way too small. These results were verified using Dymola 2017FD01 and Dymola 2018.

**Comment by Mathadon** [comment]
@beutlich I think this is one for you?:)

**Comment by tbeu** [comment]
Can you please provide the test data. Thanks.

**Comment by Mathadon** [comment]
Example .mat file:
https://www.dropbox.com/s/b7pyq0vc0d2ymbw/test.mat?dl=0 
I had to trim my source file and I can't retest the resulting data set right now but it should be ok..

**Comment by tbeu** [comment]
Cannot reproduce in SimulationX 3.8 with MSL 3.2.2 and equidistant output step size of 10s.

**Comment by beutlich** [comment]
I finally did some more tests of model [T2282](https://gist.github.com/beutlich/cafdd5274d651dac01dc6ac7e9753004) and it really looks like a tool issue to me.

**SimulationX 3.8.4:**
![t2282_simulationx](https://user-images.githubusercontent.com/14896695/29448431-e952c5e0-83f6-11e7-955d-5ad08f5c1d71.png)

**OMEdit 1.12.0\~dev-333-gaf79c51 / OpenModelica 1.12.0\~dev-960-gb53dc60:**
![t2282_openmodelica](https://user-images.githubusercontent.com/14896695/29447775-b30f33fe-83f3-11e7-9fcf-8575dbfc9b74.png)

**Dymola 2018:**
![t2282_dymola](https://user-images.githubusercontent.com/14896695/29447907-60fc64aa-83f4-11e7-92cf-b34021b218e1.png)

**MWorks.Sysplorer 2016 V4.0.2.874:**
![t2282_mworks sysplorer](https://user-images.githubusercontent.com/14896695/29447958-9fbf8ad2-83f4-11e7-9c89-364a3a109bf2.png)

**Comment by Mathadon** [comment]
Wow, that's unexpected. Thanks for looking into this in details!

**Comment by HansOlsson** [comment]
As far as I can tell the reason for the result in Dymola is that the results are stored in single precision, which means that also the time-axis is in single precision.
Thus the solution is to change settings to store in double precision, and then the results look good.

I haven't tested MWorks Sysplorer but would assume it is the same issue.

**Comment by beutlich** [comment]
Indeed, it also helps to set double precision in MWorks.Sysplorer.

![t2282_mworks sysplorer](https://user-images.githubusercontent.com/14896695/29617593-aebb33d6-8815-11e7-8214-878842522392.png)

**Comment by Mathadon** [comment]
@annvdm does this fix https://github.com/modelica/Modelica/issues/2283 ?

**Comment by beutlich** [comment]
@Mathadon #2283 is not a tool issue. It is a modeling issue.
