### ISSUE TITLE
First (and Second) Order Temperature Coefficient types misspelled in Modelica.SIunits

### ISSUE THREAD

**Issue by svorkoetter** [modelica/Modelica#2284]
These types appear in the MSL as FirstOrderTemperaturCoefficient and SecondOrderTemperaturCoefficient. The "e" is missing at the end of "Temperature". It is present in the "quantity" attribute.

**Comment by beutlich** [comment]
Introduced more than 7 years ago by 417b7d9487e9959aa4bfd9f3aa8371931597e288 without any review (see also #1435 for the other units PerArea_cm and Area_cmPerVoltageSecond added by this commit.)

**Comment by beutlich** [comment]
Resolved by #2288 in master.
