### ISSUE TITLE
Outdated Media Future

### ISSUE THREAD

**Issue by beutlich** [modelica/Modelica#2294]
[Modelica.Media.UsersGuide.Future](http://doc.modelica.org/help/Modelica_Media_UsersGuide.html#Modelica.Media.UsersGuide.Future) speaks about future version 3.1 of Modelica.Media and a beta-release in 2009. This information clearly is obsolete and shall be either removed or updated.

**Comment by Double-A-92** [comment]
Removed the whole section and references to it. Since we don't have information about plans for upcoming releases.

Will send a pull request tomorrow, so it counts to the hacktoberfest. :)
