### ISSUE TITLE
Add elementary charge of electron to Modelica.Constants

### ISSUE THREAD

**Issue by christiankral** [modelica/Modelica#2303]
The elementary charge of an electron is unfortunately not defined in ``Modelica.Constants``. As proposed in ``Modelica.Electrical.Analog.Semiconductors.HeatingDiode``, it shall be calculated as

```modelica
constant Modelica.SIunits.ElectricCharge q=Modelica.Constants.F/Modelica.Constants.N_A
      "Electron charge";
```

which gives a value of 1.602176620924561e-19 As.

**Comment by thorade** [comment]
Also see discussion in #1241 and possibly #2207
