### ISSUE TITLE
Very complex C code

### ISSUE THREAD

**Issue by DagBruck** [modelica/Modelica#2306]
In ModelicaStandardTable.c, around line 4387 but possibly elsewhere, I find the construct

`((__GLIBC__ << 16) + __GLIBC_MINOR__ >= (2 << 16) + 3)`

Could that possibly be re-written as

`(__GLIBC__ >= 2 && __GLIBC_MINOR__ >= 3)`

I'm all in favor of simple code.

**Comment by HansOlsson** [comment]
But that isn't right? Shouldn't it be ` ((__GLIBC__ >= 2 && __GLIBC_MINOR__ >= 3)  || __GLIBC__>2)` -  and then I'm not sure if it is simpler.

**Comment by beutlich** [comment]
It basically is the resolved [__GLIBC_PREREQ](https://github.com/lattera/glibc/blob/master/include/features.h#L361-L362) macro.

**Comment by beutlich** [comment]
I won't touch it for now.
