### ISSUE TITLE
Reference to very old Dymola versions in MSL documentation: remove all tool specific documentation from MSL

### ISSUE THREAD

**Issue by hubertus65** [modelica/Modelica#2322]
It was reported that there are still references to old Dymola version in the documentation of MSL. There should be no tool specific references in MSL. Vendors could add that on their own, but there should be none in the MA released version.

**Comment by beutlich** [comment]
I assume @hubertus65  only ment the first one, as this issue was labled with L: Fluid.

**Comment by beutlich** [comment]
See #2294 for a similar issue with outdated documentation (from 2009).

**Comment by jdalrymple** [comment]
Is anyone working on this yet?

**Comment by beutlich** [comment]
Resolved by c949a41ecd0ae2392daf14c7a974a47ee0c60aa3 in master.
