### ISSUE TITLE
New tool vendor annotation added to MSL which must be removed

### ISSUE THREAD

**Issue by dietmarw** [modelica/Modelica#2332]
In https://github.com/modelica/Modelica/commit/45dbd758d8a34ae50d15365c67f4552db2e37df9 and b2e80699505f512d988d2b7d2df6cb23e674be96 a tool vendor annotation was introduced (probably by mistake). This needs to be removed again. The MA is very clear on the principle that although the specification allows tool vendor specific annotations marked with the prefix `__ToolVendor_` those should not be present in the tool neutral Modelica Standard Library. We have spent the last 10 years gradually removing all those `__Dymola_` annotation and simply can not start adding new ones again. 

So please remove those annotations again. If specific tool features are needed then those models should be in a custom library outside the MSL.

**Comment by christiankral** [comment]
No, I inserted it intentionally. But reading your ticket, I start remembering, that we do not want to have vendor specific annotations in the MSL... 

So I removed the annotations in 2f1f95a and 24cab71.
