### ISSUE TITLE
EddyCurrent using non-resistance resistance-function

### ISSUE THREAD

**Issue by HansOlsson** [modelica/Modelica#2379]
The tests for #2375 detected another issue that required a bit extra to identify.
The models
Modelica.Mechanics.Rotational.Sources.EddyCurrentTorque
Modelica.Mechanics.Translational.Sources.EddyCurrentForce
use Modelica.Electrical.Machines.Thermal.convertResistance - for something that isn't a Resistance, but just a number with unit "1".

Thus it fails a unit-check. 

I don't know if the solution is to add a variant of convertResistance (with better name) - or remove unit from the existing convertResistance.

**Comment by MartinOtter** [comment]
These are models from Anton Haumer

**Comment by AHaumer** [comment]
I'll add a function linearTemperatureDependency which does the same as convertResistance but without physical units for input RRef and result R.
