### ISSUE TITLE
Missing test or example model for Modelica.Utilities.Files.list

### ISSUE THREAD

**Issue by beutlich** [modelica/Modelica#2391]
There is neither a sample nor a test model for Modelica.Utilities.Files.list. Thus, #2387 was a hidden issue and not covered by regression tests.

**Comment by GallLeo** [comment]
I added pull request #2392. I tried to link the pull request to this issue, by adding "resolves #2391" to the comment line. This does not seem to work ... *Github noob*

**Comment by beutlich** [comment]
> I added pull request

Thanks.

> This does not seem to work 

It will, as soon as your pull request is merged. See https://help.github.com/articles/closing-issues-using-keywords/.

**Comment by HansOlsson** [comment]
I believe that this is related to #2259 - i.e. it was difficult to construct a good test-case for the function since it was hard to find a good use for it.
