### ISSUE TITLE
Error in documentation for InlineAfterIndexReduction

### ISSUE THREAD

**Issue by GarronFish** [modelica/Modelica#2394]
On page 233 in ModelicaSpec34.pdf

Documentation states:
[This annotation is for example used in Modelica.Mechanics.Rotational.Sources.Move to define that an input signal is the derivative of another input signal.]

However now LateInline=true is used since modifications in ticket #1523.

**Comment by beutlich** [comment]
Looks like this should have been reported at https://trac.modelica.org/Modelica/.

**Comment by GarronFish** [comment]
Which tickets should be reported at https://trac.modelica.org/Modelica/ and which should be report here?

**Comment by beutlich** [comment]
Library tickets go here, Specification tickets remain on Trac.

**Comment by HansOlsson** [comment]
This is now migrated to: https://trac.modelica.org/Modelica/ticket/2222
@GarronFish I did not CC you on the Modelica-ticket; if you want that it would be straightforward.
