### ISSUE TITLE
MassFractionsTwoPort — code bug

### ISSUE THREAD

**Issue by justnielsen** [modelica/Modelica#2406]
In `Modelica.Fluid.Sensors.MassFractionsTwoPort` there is a `for` loop in the `initial algorithm` section iterating from `1:Medium.nC`. This should be changed to `1:Medium.nXi`.

**Comment by beutlich** [comment]
This line: https://github.com/modelica/Modelica/blob/23ce318d3e30ac2972ee140825c482dc874dd172/Modelica/Fluid/Sensors.mo#L462

**Comment by sjoelund** [comment]
Could simply be an initial equation without algorithm or anything fancy:
```mo
assert(max(name == substanceName for name in Medium.substanceNames), "Mass fraction '" + substanceName + "' is not present in medium '"
           + Medium.mediumName + "'.\n"
           + "Check sensor parameter and medium model.");
```

**Comment by beutlich** [comment]
The `max` seems odd. Is there a `break` statement missing in all these loops (also MassFractions, TraceSubstances and TraceSubstancesTwoPort)?

**Comment by sjoelund** [comment]
`max` may seem weird, but it's the Modelica way of checking if some element of an array is true. It also avoids temporary variables which become part of result files (if protected variables are included).

**Comment by wischhusen** [comment]
We need "ind" below in the equation part to access the right substance. I think I will stick to the existing initial algorithm. But nice idea.

**Comment by beutlich** [comment]
@wischhusen Will you file a PR from your branch or simply merge it yourself?
