### ISSUE TITLE
Add parameter "radius" to icon of IdealRollingWheel

### ISSUE THREAD

**Issue by christiankral** [modelica/Modelica#2423]
In the model ```IdealRollingWheel``` of the Rotational and Translational package, the parameter ```%radius``` is not displayed in the icon representation. This shall be fixed.

**Comment by tobolar** [comment]
It is fine when you do the modifications since there is less effort for me. Additionally, triggering a pull request would be more preferable way for it enables me to easily follow and merge the changes.
