### ISSUE TITLE
Redundancy in Modelica.Mechanics.MultiBody.Sensors.Internal

### ISSUE THREAD

**Issue by tobolar** [modelica/Modelica#2426]
There is some redundancy of classes in `Modelica.Mechanics.MultiBody.Sensors.Internal` and `Modelica.Mechanics.MultiBody.Interfaces.PartialAbsoluteSensor` or `Modelica.Mechanics.MultiBody.Interfaces.PartialRelativeSensor`.
E.g. `Sensors.Internal.PartialAbsoluteSensor` should be used as base class of `Interfaces.PartialAbsoluteSensor`, etc.

**Comment by beutlich** [comment]
See #2171 for a similar issue.

**Comment by tobolar** [comment]
I have tried to clean as much as possible in cfcdb056c0e1bca136ac3f724c3a936a87057bbd. May be there is a possibility to do more but then it would be issue for the next major version of MSL.
