### ISSUE TITLE
Fix inconsistent naming of newly introduced quasi static MultiSensor 

### ISSUE THREAD

**Issue by christiankral** [modelica/Modelica#2483]
The multi sensors of both the quasi statsic SinglePhase and MultiPhase package are inconsistently named. The names shall be changed to match the former introduced naming convention of the packages.
- i_abs -> abs_i
- i_arg -> arg_i
- v_abs -> abs_v
- v_arg -> arg_v

... an so on

**Comment by christiankral** [comment]
The fix is backwards compatible, since these components have not yet been released.

**Comment by beutlich** [comment]
Reset milestone such that #2483 does not show up in the (later) Release Notes.
