### ISSUE TITLE
Animation missing in MultiBody.Forces.SpringDamperSeries

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#386]
**Reported by otter on 22 Jul 2010 10:19 UTC**
The component MultiBody.Forces.SpringDamperSeries does not yet have animation 

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/386

**Comment by modelica-trac-importer** [comment]
**Modified by otter on 5 Aug 2010 21:37 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 6 Sep 2012 11:57 UTC**
These tickets don't rely on conversion scripts, hence rescheduling for the next major release

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 29 Apr 2014 06:29 UTC**
@dietmarw: Should Milestone be set back to MSL_withConversionScript?

**Comment by modelica-trac-importer** [comment]
**Changelog removed by beutlich on 29 Apr 2014 06:29 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by otter on 13 Dec 2015 08:05 UTC**
Do not yet have time to provide an animation. Feel free to propose an animation object and send a patch

**Comment by beutlich** [comment]
> Feel free to propose an animation object and send a patch

@MartinOtter Done by #2183. Please check the proposed animation enhancements for  SpringDamperSeries and SpringDamperParallel.

**Comment by beutlich** [comment]
Resolved in master by #2183.
